name: dash_crypt
description: >
  DashCrypt is a powerful and flexible encryption and decryption package for Flutter and Dart. 
  It supports a wide range of modern and classical cryptographic algorithms, making it ideal 
  for developers looking to integrate secure encryption into their projects. DashCrypt also 
  provides utilities for secure key and IV generation, ensuring robust security. Designed 
  for simplicity, performance, and scalability, DashCrypt is the perfect solution for all 
  your encryption needs.
version: 0.0.1+2
homepage: https://ahmed-ayman.framer.ai/
repository: https://github.com/Ahmad-Ayman/dash_crypt

environment:
  sdk: ">=3.0.0 <4.0.0" # Minimum Dart SDK version required by your plugin
  flutter: ">=3.0.0"    # Minimum Flutter SDK version required by your plugin

dependencies:
  flutter:
    sdk: flutter
  pointycastle: any
  encrypt: any
  cryptography: any
  convert: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
